.TH PyRoom 1 "01 Mar 2009"
.SH NAME
\fBPyRoom\fP \- distraction-free writing

.SH DESCRIPTION
.fi
.B PyRoom
lets you edit text files simply and efficiently in a full-screen window, with no distractions.
.nf
.LP
.SH OPTIONS

.TP
\fB\-\-help\fR
Prints the command line options and exits..
.TP
\fB\-\-version\fR
Prints the programm's version and exits.
.TP
\fBfilename(s)...\fR
Specifies the file to open
.SH BUGS
If you find a bug, please report it at 

.B http://launchpad.net/pyroom
.SH AUTHORS
The PyRoom Team
